const $=id=>document.getElementById(id);const fmt=n=>Math.round(Number(n)||0).toLocaleString('id-ID');const localDate=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};const parseDate=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};const offsetDate=(s,delta)=>{const d=parseDate(s);d.setDate(d.getDate()+delta);return localDate(d)};const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let staticFoods=[],customFoods=[],allFoods=[],logs=[],weights=[],favorites=[],packs=[],profile={sex:'male',age:30,weight:70,height:170,activity:1.375,goal:-250};let currentPage='today',historyDate=localDate(),dbSource='Semua',dbCategory='Semua',addMode='recent',installPrompt=null,scannerStream=null,scanTimer=null;
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function foodSearchNorm(s){return String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\btelor\b/g,'telur').replace(/\bsego\b/g,'nasi').replace(/\bsambel\b/g,'sambal').replace(/\bgethuk\b/g,'getuk').replace(/\bmata sapi\b/g,'ceplok').replace(/\bmie\b/g,'mi').replace(/\bbakmie\b/g,'bakmi').replace(/\bsup\b/g,'sop').replace(/\btoge\b/g,'tauge').replace(/\btempeh\b/g,'tempe').replace(/\bcoklat\b/g,'cokelat').replace(/\bcappucino\b/g,'cappuccino').replace(/\bkwetiaw\b/g,'kwetiau').replace(/\bkrispi\b/g,'crispy').replace(/\bbaso\b/g,'bakso').replace(/\bnasgor\b|\bnasi grg\b/g,'nasi goreng').replace(/\bmigor\b|\bmi grg\b/g,'mi goreng').replace(/\bgrg\b/g,'goreng').replace(/\brbs\b/g,'rebus').replace(/\baym\b/g,'ayam').trim().replace(/\s+/g,' ')}
function foodSearchNames(f){return [f.name,...(Array.isArray(f.aliases)?f.aliases:[])].map(foodSearchNorm)}
// Restricted Damerau-Levenshtein: includes adjacent swapped letters.
function foodTypoDistance(a,b,limit){
 if(Math.abs(a.length-b.length)>limit)return limit+1;
 let prev=Array.from({length:b.length+1},(_,i)=>i),older=null;
 for(let i=1;i<=a.length;i++){
  const row=[i];let min=i;
  for(let j=1;j<=b.length;j++){
   let n=Math.min(prev[j]+1,row[j-1]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));
   if(older&&i>1&&j>1&&a[i-1]===b[j-2]&&a[i-2]===b[j-1])n=Math.min(n,older[j-2]+1);
   row[j]=n;min=Math.min(min,n);
  }
  if(min>limit)return limit+1;older=prev;prev=row;
 }
 return prev[b.length];
}
function foodSearchScore(f,q){
 const b=foodSearchNorm(q);if(!b)return 0;
 const signature=String(f.name)+'|'+JSON.stringify(f.aliases||[]);
 const cache=foodSearchScore.cache||(foodSearchScore.cache=new WeakMap());let entry=cache.get(f);
 if(!entry||entry.signature!==signature){entry={signature,names:foodSearchNames(f),query:null};cache.set(f,entry)}
 if(entry.query===b)return entry.score;
 const names=entry.names,main=names[0],words=b.split(' ');
 let score=Infinity;
 if(main===b)score=0;else if(main.startsWith(b))score=1;else if(names.includes(b))score=2;
 else if(names.some(a=>a.startsWith(b)))score=3;else if(main.includes(b))score=4;
 else if(names.some(a=>a.includes(b)||words.every(w=>a.split(' ').includes(w))))score=5;
 else if(b.replace(/ /g,'').length>=5&&names.some(a=>a.replace(/ /g,'').includes(b.replace(/ /g,'')))){const compact=b.replace(/ /g,'');score=main.replace(/ /g,'')===compact?5.1:names.some(a=>a.replace(/ /g,'')===compact)?5.2:5.5;}
 else {
  for(const name of names){
   const tokens=name.split(' ');let cost=0;let matched=true;
   for(const word of words){
    let best=Infinity;
    for(const token of tokens){
     if(token===word){best=0;break}
     if(word.length>=3&&token.startsWith(word)){best=Math.min(best,.25);continue}
     // Short words and numbers require exact spelling to avoid unrelated results.
     if(word.length<4||token.length<4||/\d/.test(word+token))continue;
     const limit=word.length>=7?2:1,n=foodTypoDistance(word,token,limit);
     if(n<=limit)best=Math.min(best,n);
    }
    if(!Number.isFinite(best)){matched=false;break}cost+=best;
   }
   if(matched)score=Math.min(score,6+cost+Math.max(0,tokens.length-words.length)*.01);
  }
 }
 entry.query=b;entry.score=score;return score;
}
function foodMatches(f,q){return Number.isFinite(foodSearchScore(f,q))}
function foodMatchRank(f,q){return foodSearchScore(f,q)}
function foodSearchLabel(f,q){
 if(!foodSearchNorm(q))return '';
 const score=foodSearchScore(f,q);if(!Number.isFinite(score))return '';
 return score>=6?'Ejaan mendekati':score>5&&score<6?'Spasi disesuaikan':'Cocok kata';
}
function foodSearchBadge(f,q){const label=foodSearchLabel(f,q);return label?'<span class="badge '+(label==='Ejaan mendekati'?'v27-approx':'v27-match')+'">'+label+'</span>':'';}
function sourceLabel(t){return t==='tkpi'?'TKPI':t==='calculated'?'TKPI (konversi)':t==='label'?'Label produk':t==='openfoodfacts'?'Open Food Facts':t==='user'?'Custom':'Estimasi'}function badge(f){const t=f.source_type||f.sourceType||'estimate',cl=t==='tkpi'||t==='calculated'?'tkpi':t==='label'?'label':t==='openfoodfacts'?'off':'';return `<span class="badge ${cl}">${t==='tkpi'?(f.verification_status==='name_code_matched_macro_pending'?'TKPI (kode cocok)':f.verification_status==='matched_duplicate_code_alias'?'TKPI (alias)':f.tkpi_code?'TKPI (rujukan)':'TKPI (kode belum dicatat)'):sourceLabel(t)}</span>`}function nutrientMismatch(f){const c=Number(f.calories),p=Number(f.protein),k=Number(f.carbs),fat=Number(f.fat);if(![c,p,k,fat].every(Number.isFinite))return false;return Math.abs((p+k)*4+fat*9-c)>Math.max(30,c*.2)}
function calcTarget(p=profile){const w=+p.weight,h=+p.height,a=+p.age;const bmr=p.sex==='male'?10*w+6.25*h-5*a+5:10*w+6.25*h-5*a-161;const tdee=bmr*(+p.activity);const cal=Math.max(1200,Math.round(tdee+(+p.goal)));const dProtein=Math.round(w*1.6),dFat=Math.round(cal*.27/9),dCarb=Math.max(0,Math.round((cal-dProtein*4-dFat*9)/4)),m=p.macroTargets||{};const safe=(v,d,max)=>v===undefined||v===null||v===''?d:Math.max(0,Math.min(max,Number(v)||0));const protein=safe(m.protein,dProtein,600),fat=safe(m.fat,dFat,300),carb=safe(m.carb,dCarb,900);return{bmr:Math.round(bmr),tdee:Math.round(tdee),cal,protein,fat,carb}}
function total(a){return a.reduce((x,l)=>({cal:x.cal+l.calories*l.qty,p:x.p+l.protein*l.qty,c:x.c+l.carbs*l.qty,f:x.f+l.fat*l.qty}),{cal:0,p:0,c:0,f:0})}
async function init(){staticFoods=await Promise.all([fetch('./data/foods.json').then(r=>r.json()),fetch('./data/foods-daily.json').then(r=>{if(!r.ok)throw Error('Katalog harian gagal dimuat');return r.json()}),fetch('./data/foods-regional.json').then(r=>{if(!r.ok)throw Error('Katalog daerah gagal dimuat');return r.json()}),fetch('./data/foods-extra.json').then(r=>r.ok?r.json():[]).catch(()=>[]),fetch('./data/foods-expanded.json').then(r=>{if(!r.ok)throw Error('Katalog tambahan gagal dimuat');return r.json()}),fetch('./data/foods-tkpi-2017.json').then(r=>{if(!r.ok)throw Error('Katalog TKPI 2017 gagal dimuat');return r.json()}),fetch('./data/foods-tkpi-2020.json').then(r=>{if(!r.ok)throw Error('Katalog TKPI 2020 gagal dimuat');return r.json()})]).then(([primary,daily,regional,extra,expanded,tkpi2017,tkpi2020])=>{const seen=new Set();return [...primary,...daily,...regional,...extra,...expanded,...tkpi2017,...tkpi2020].filter(f=>{const k=foodSearchNorm(f.name);if(seen.has(k))return false;seen.add(k);return true})});[customFoods,logs,weights,profile,favorites,packs]=await Promise.all([dbAll('customFoods'),dbAll('logs'),dbAll('weights'),dbGetKV('profile',profile),dbGetKV('favorites',[]),dbGetKV('packs',[])]);allFoods=[...staticFoods,...customFoods];historyDate=localDate();wire();updateOnline();renderAll();registerSW();}
function wire(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('fab').onclick=openAdd;$('copyYesterdayBtn').onclick=copyYesterday;$('openWeightQuick').onclick=openWeight;$('addWeightBtn').onclick=openWeight;$('histPrev').onclick=()=>{historyDate=offsetDate(historyDate,-1);renderHistory()};$('histNext').onclick=()=>{if(historyDate<localDate())historyDate=offsetDate(historyDate,1);renderHistory()};$('histDate').onchange=e=>{historyDate=e.target.value;renderHistory()};$('dbSearch').oninput=renderDatabase;$('addCustomBtn').onclick=openCustom;$('foodSearch').oninput=renderAddResults;$('qtyInput').oninput=renderAddResults;$('quickInput').oninput=renderQuickPreview;document.querySelectorAll('#addModeChips .chip').forEach(b=>b.onclick=()=>{addMode=b.dataset.mode;document.querySelectorAll('#addModeChips .chip').forEach(x=>x.classList.toggle('on',x===b));renderAddResults()});$('customForm').addEventListener('submit',saveCustom);$('weightForm').addEventListener('submit',saveWeight);$('saveProfileBtn').onclick=saveProfile;$('backupBtn').onclick=backup;$('restoreBtn').onclick=()=>$('restoreFile').click();$('restoreFile').onchange=e=>restore(e.target.files[0]);$('csvBtn').onclick=exportCSV;$('sexSegment').onclick=e=>{if(e.target.dataset.v){profile.sex=e.target.dataset.v;renderProfileFields()}};$('scanBtn').onclick=startScanner;$('closeScanner').onclick=stopScanner;$('manualLookup').onclick=()=>lookupBarcode($('manualBarcode').value.trim());window.addEventListener('online',updateOnline);window.addEventListener('offline',updateOnline);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;showInstall()});$('installBtn').onclick=installPWA;$('installBtn2').onclick=installPWA;}
function go(page){currentPage=page;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${page}`));document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const titles={today:['Hari Ini',new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long'})],history:['Riwayat','Catatan konsumsi per hari'],database:['Database','Pangan, menu, dan produk'],stats:['Statistik','Tren konsumsi dan berat badan'],profile:['Profil','Target dan penyimpanan data']};$('pageTitle').textContent=titles[page][0];$('pageSub').textContent=titles[page][1];$('fab').classList.toggle('hidden',!['today','history'].includes(page));if(page==='history')renderHistory();if(page==='database')renderDatabase();if(page==='stats')renderStats();if(page==='profile')renderProfile()}
function renderAll(){renderToday();renderHistory();renderDatabase();renderStats();renderProfile();$('foodCountProfile').textContent=`${allFoods.length.toLocaleString('id-ID')} entri`;}
function renderToday(){const a=logs.filter(l=>l.date===localDate()).sort((x,y)=>x.createdAt-y.createdAt),t=total(a),g=calcTarget();$('todayCal').textContent=fmt(t.cal);$('targetCal').textContent=fmt(g.cal);$('calProgress').style.width=Math.min(100,t.cal/g.cal*100)+'%';const rem=g.cal-t.cal;$('remainingText').textContent=rem>=0?`Sisa ${fmt(rem)} kcal`:`Lebih ${fmt(-rem)} kcal`;$('todayItemCount').textContent=`${a.length} item`;$('todayKcalSmall').textContent=`${fmt(t.cal)} kcal`;$('macroRows').innerHTML=macroRow('Protein',t.p,g.protein)+macroRow('Karbohidrat',t.c,g.carb)+macroRow('Lemak',t.f,g.fat);$('todayLogs').innerHTML=mealGroups(a,true);if(typeof v27RenderRepeat==='function')v27RenderRepeat()}
function macroRow(n,v,g){return `<div class="macro-line"><div class="macro-top"><span>${n}</span><span>${fmt(v)} / ${g} g</span></div><div class="mini-progress"><span style="width:${(g>0?Math.min(100,v/g*100):(v>0?100:0))}%"></span></div></div>`}
function mealGroups(a,canPack=false){if(!a.length)return'<article class="card empty">Belum ada catatan.</article>';return ['Sarapan','Makan Siang','Makan Malam','Snack','Minuman'].map(m=>{const g=a.filter(x=>x.meal===m);if(!g.length)return'';const kcal=total(g).cal;return `<article class="card meal-card"><div class="meal-head"><strong>${m}</strong><small>${fmt(kcal)} kcal</small>${canPack?`<button class="text-btn" onclick="saveMealPack('${m}')">Simpan paket</button>`:''}</div>${g.map(logRow).join('')}</article>`}).join('')}
function logRow(l){return `<div class="log-row"><div class="log-info"><strong>${esc(l.name)}</strong><small>${l.qty} × ${esc(l.serving)}</small></div><b>${fmt(l.calories*l.qty)} kcal</b><button class="secondary log-edit-btn" type="button" onclick="editKaloriLog('${l.id}')">Edit</button><button class="del" onclick="removeLog('${l.id}')">×</button></div>`}
async function removeLog(id){await dbDelete('logs',id);logs=logs.filter(x=>x.id!==id);renderToday();renderHistory();renderStats()}
async function copyYesterday(){const y=offsetDate(localDate(),-1),a=logs.filter(x=>x.date===y);for(const l of a){const n={...l,id:'l_'+crypto.randomUUID(),date:localDate(),createdAt:Date.now()+Math.random()};await dbPut('logs',n);logs.push(n)}toast(a.length?`${a.length} item disalin`:'Kemarin belum ada catatan');renderToday();}
function renderHistory(){$('histDate').value=historyDate;const a=logs.filter(x=>x.date===historyDate).sort((x,y)=>x.createdAt-y.createdAt),t=total(a);$('histDateLabel').textContent=parseDate(historyDate).toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('histKcal').textContent=`${fmt(t.cal)} kcal · ${a.length} item`;$('histNext').disabled=historyDate>=localDate();$('historyLogs').innerHTML=mealGroups(a,false)}
function initFilterChips(){const sources=['Semua','TKPI','TKPI (konversi)','Estimasi','Label produk','Open Food Facts','Custom'],cats=['Semua',...new Set(allFoods.map(f=>f.category))];$('sourceChips').innerHTML=sources.map(s=>`<button class="chip ${s===dbSource?'on':''}" onclick="setDbSource('${s}')">${s}</button>`).join('');$('categoryChips').innerHTML=cats.map((s,i)=>`<button class="chip ${s===dbCategory?'on':''}" onclick="setDbCategory(${JSON.stringify(s)})">${esc(s)}</button>`).join('')}
window.setDbSource=s=>{dbSource=s;renderDatabase()};window.setDbCategory=s=>{dbCategory=s;renderDatabase()};
function renderDatabase(){initFilterChips();const q=$('dbSearch').value.trim().toLowerCase(),a=allFoods.filter(f=>(dbSource==='Semua'||sourceLabel(f.source_type||f.sourceType)===dbSource)&&(dbCategory==='Semua'||f.category===dbCategory)&&(!q||foodMatches(f,q))).sort((a,b)=>foodMatchRank(a,q)-foodMatchRank(b,q));const tkpi=allFoods.filter(f=>(f.source_type||f.sourceType)==='tkpi').length,calc=allFoods.filter(f=>f.source_type==='calculated').length,noCode=allFoods.filter(f=>f.source_type==='tkpi'&&!f.tkpi_code).length,uniqueTkpiCodes=new Set(allFoods.filter(f=>f.source_type==='tkpi'&&f.tkpi_code).map(f=>f.tkpi_code)).size,tkpiAliases=allFoods.filter(f=>f.source_type==='tkpi'&&f.tkpi_alias_of).length;$('dbStats').textContent=`${allFoods.length.toLocaleString('id-ID')} entri · ${tkpi} rujukan TKPI (${uniqueTkpiCodes} kode unik, ${tkpiAliases} alias; ${noCode} tanpa kode) · ${calc} konversi porsi · ${customFoods.length} custom/produk`;$('dbResults').innerHTML=a.slice(0,120).map(f=>`<article class="card food-card">${foodCard(f,false,q)}</article>`).join('')+(a.length>120?`<div class="empty">Menampilkan 120 dari ${a.length}. Persempit pencarian.</div>`:'')}
function foodCard(f,add=true,q=''){const fav=favorites.includes(f.id),meta=(f.source_type==='tkpi'&&f.bdd_percent)?` · BDD ${f.bdd_percent}%`:(f.source_type==='calculated'?' · Dihitung dari porsi 100 g BDD':''),edition=f.tkpi_edition,crosschecked=f.tkpi_edition_crosschecked,sourceCode=f.tkpi_code?` · ${esc(f.tkpi_code)}${edition?' (ed. '+edition+')':crosschecked?' (dicocokkan '+crosschecked+')':''}`:'',known=k=>typeof f[k]==='number'&&Number.isFinite(f[k])&&f[k]>=0,formatKnown=k=>Number(f[k]).toLocaleString('id-ID',{maximumFractionDigits:2}),nutrients=known('fiber')||known('sodium')?`<div class="food-meta">${known('fiber')?'Serat '+formatKnown('fiber')+' g':''}${known('fiber')&&known('sodium')?' · ':''}${known('sodium')?'Natrium '+formatKnown('sodium')+' mg':''} <span title="Nilai dari salinan tabel TKPI, bukan pengukuran langsung">· ${f.source_type==='tkpi'||f.source_type==='calculated'?'TKPI 2020 (salinan)':'Sesuai data per porsi'}</span></div>`:'',warn=f.source_code_conflict?'⚠ Kode tabel dan indeks TKPI berbeda':f.verification_status==='printed_source_conflict'?'⚠ Angka berbeda dengan tabel TKPI: perlu verifikasi':nutrientMismatch(f)?'⚠ Kalori dan makro perlu verifikasi':'',flag=(f.verification_status==='name_code_matched_macro_pending'?'<div class="food-meta">Kode sumber cocok; angka gizi perlu audit per baris</div>':f.verification_status==='matched_duplicate_code_alias'?'<div class="food-meta">Alias kode sumber TKPI AP005 (bukan entri baru)</div>':'')+(f.macro_verification_status==='transcription_crosschecked_original_pending'?'<div class="food-meta">Energi dan makro cocok dengan salinan TKPI; PDF primer dan BDD belum diperiksa lengkap</div>':f.macro_verification_status==='primary_pdf_crosschecked'?'<div class="food-meta">Energi dan makro cocok dengan PDF TKPI Kemenkes</div>':'')+(warn?`<div class="food-meta" style="color:#b45309">${warn}</div>`:'');return `<div class="food-icon">🍽</div><div class="food-info"><strong>${esc(f.name)}</strong><div class="food-meta">${esc(f.serving)} · ${fmt(f.calories)} kcal · P ${fmt(f.protein)} · K ${fmt(f.carbs)} · L ${fmt(f.fat)}</div>${foodSearchBadge(f,q)} ${badge(f)}<span class="food-meta">${meta}${sourceCode}</span>${nutrients}${flag}</div><button class="fav-btn ${fav?'on':''}" onclick="toggleFav('${f.id}')">${fav?'★':'☆'}</button>${add?`<button class="add-btn" onclick="addFood('${f.id}')">＋</button>`:''}`}
async function toggleFav(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];await dbSetKV('favorites',favorites);renderAddResults();renderDatabase()}
function openAdd(){$('entryDate').value=currentPage==='history'?historyDate:localDate();$('entryDate').max=localDate();$('addDialog').showModal();$('foodSearch').value='';$('quickInput').value='';renderQuickPreview();renderAddResults()}
function renderAddResults(){const q=$('foodSearch').value.trim().toLowerCase();let a=[];if(q)a=allFoods.filter(f=>foodMatches(f,q)).sort((a,b)=>foodMatchRank(a,q)-foodMatchRank(b,q));else if(addMode==='favorite')a=allFoods.filter(f=>favorites.includes(f.id));else if(addMode==='recent'){const ids=[...logs].sort((a,b)=>b.createdAt-a.createdAt).map(x=>x.foodId).filter((x,i,z)=>z.indexOf(x)===i).slice(0,20);a=ids.map(id=>allFoods.find(f=>f.id===id)).filter(Boolean)}else if(addMode==='packs'){renderPacks();return}else a=allFoods;$('addResults').innerHTML=a.slice(0,90).map(f=>`<div class="log-row">${foodCard(f,true,q)}</div>`).join('')||'<div class="empty">Belum ada item.</div>'}
function renderPacks(){$('addResults').innerHTML=packs.length?packs.map(p=>`<div class="log-row"><div class="food-info"><strong>${esc(p.name)}</strong><div class="food-meta">${p.items.length} item · ${fmt(p.items.reduce((s,i)=>s+i.calories*i.qty,0))} kcal</div></div><button class="add-btn" onclick="addPack('${p.id}')">＋</button></div>`).join(''):'<div class="empty">Belum ada paket. Simpan dari kelompok makan Hari Ini.</div>'}
async function addFood(id){const f=allFoods.find(x=>x.id===id);if(!f)return;const amount=Number($('qtyInput').value),unit=$('qtyUnit').value,unitGrams=typeof v14UnitGrams==='function'?v24UnitFor(unit,f):null,baseGrams=typeof v14ServingGrams==='function'?v14ServingGrams({foodId:f.id,serving:f.serving}):null;if(Number.isNaN(unitGrams)){toast('Takaran ini belum diketahui untuk makanan tersebut. Gunakan porsi/gram atau Atur takaran.');return}if(!Number.isFinite(amount)||amount<=0){toast('Jumlah harus positif');return}if(unitGrams!==null&&!baseGrams){toast('Berat porsi belum tersedia. Pilih porsi.');return}const q=unitGrams===null?Math.max(.1,amount):Math.max(.01,amount*unitGrams/baseGrams),l={id:'l_'+crypto.randomUUID(),date:$('entryDate').value||localDate(),meal:$('mealSelect').value,foodId:f.id,name:f.name,serving:f.serving,servingGrams:baseGrams,qty:q,calories:+f.calories,protein:+f.protein,carbs:+f.carbs,fat:+f.fat,...v17NutrientSnapshot(f),createdAt:Date.now()};await dbPut('logs',l);logs.push(l);toast(`${f.name} ditambahkan`);renderToday();renderHistory();renderStats();renderAddResults();}
function parseQuick(s){const chunks=s.toLowerCase().replace(/\s+dan\s+/g,',').replace(/\s*\+\s*/g,',').split(',').map(x=>x.trim()).filter(Boolean),out=[];for(const ch of chunks){const m=ch.match(/(?:^|\s)(\d+(?:[.,]\d+)?)/),qty=m?Number(m[1].replace(',','.')):1,clean=ch.replace(/\b\d+(?:[.,]\d+)?\b/g,' ').replace(/\b(x|porsi|buah|butir|gelas|potong|centong|mangkuk|bungkus|tusuk)\b/g,' ').replace(/\s+/g,' ').trim();const candidates=clean?allFoods.filter(f=>foodMatches(f,clean)):[];candidates.sort((a,b)=>foodMatchRank(a,clean)-foodMatchRank(b,clean)||score(foodSearchNorm(a.name),foodSearchNorm(clean))-score(foodSearchNorm(b.name),foodSearchNorm(clean)));if(candidates[0])out.push({food:candidates[0],qty:Math.max(.1,qty),raw:ch})}return out}function score(name,q){if(name===q)return 0;if(name.startsWith(q))return 1;return Math.abs(name.length-q.length)+5}
function renderQuickPreview(){const s=$('quickInput').value.trim(),p=parseQuick(s);if(!s){$('quickPreview').innerHTML='';return}$('quickPreview').innerHTML=p.length?`<div class="info-note">${p.map(x=>`${esc(x.food.name)} × ${x.qty}`).join('<br>')}<button class="primary full" style="margin-top:8px" onclick="commitQuick()">Catat semua</button></div>`:'<div class="info-note" style="background:#fff7ed;color:#92400e">Belum ada makanan yang cocok.</div>'}
window.commitQuick=async()=>{const p=parseQuick($('quickInput').value);const oldUnit=$('qtyUnit').value;$('qtyUnit').value='porsi';for(const x of p){$('qtyInput').value=x.qty;await addFood(x.food.id)}$('qtyUnit').value=oldUnit;$('quickInput').value='';$('qtyInput').value=1;renderQuickPreview();toast(`${p.length} item dicatat`)};
window.saveMealPack=async meal=>{const items=logs.filter(l=>l.date===localDate()&&l.meal===meal);if(!items.length)return;const name=prompt('Nama paket',`${meal} favorit`);if(!name)return;packs.push({id:'p_'+crypto.randomUUID(),name,items:items.map(({foodId,name,serving,qty,calories,protein,carbs,fat,...rest})=>({foodId,name,serving,qty,calories,protein,carbs,fat,...v17NutrientSnapshot(rest)}))});await dbSetKV('packs',packs);toast('Paket tersimpan')};window.addPack=async id=>{const p=packs.find(x=>x.id===id);for(const i of p.items){const l={...i,id:'l_'+crypto.randomUUID(),date:$('entryDate').value||localDate(),meal:$('mealSelect').value,createdAt:Date.now()+Math.random()};await dbPut('logs',l);logs.push(l)}renderToday();toast('Paket ditambahkan')};
function openCustom(){$('customDialog').showModal()}
async function saveCustom(e){e.preventDefault();const f={id:'custom_'+crypto.randomUUID(),name:$('customName').value.trim(),category:'Custom',serving:$('customServing').value.trim(),calories:Number($('customCal').value)||0,protein:Number($('customP').value)||0,carbs:Number($('customC').value)||0,fat:Number($('customF').value)||0,source_type:$('customBarcode').value?'label':'user',source_ref:$('customBarcode').value?'Diinput dari label produk':'Input pengguna',barcode:$('customBarcode').value.trim(),...v17ReadOptionalNutrients('custom')};if(!f.name||!f.serving)return;await dbPut('customFoods',f);customFoods.push(f);allFoods=[...staticFoods,...customFoods];$('customForm').reset();$('customDialog').close();renderDatabase();renderAddResults();if(typeof v15RenderAudit==='function')v15RenderAudit();toast('Makanan disimpan')}
function openWeight(){$('weightDate').value=localDate();$('weightValue').value=profile.weight||'';$('weightDialog').showModal()}
async function saveWeight(e){e.preventDefault();const w={date:$('weightDate').value,weight:Number($('weightValue').value)};if(!w.date||!w.weight)return;await dbPut('weights',w);weights=weights.filter(x=>x.date!==w.date);weights.push(w);weights.sort((a,b)=>a.date.localeCompare(b.date));$('weightDialog').close();renderStats();toast('Berat badan tersimpan')}
function renderStats(){const days=[];for(let i=13;i>=0;i--){const d=offsetDate(localDate(),-i),t=total(logs.filter(x=>x.date===d));days.push({date:d,cal:t.cal})}const last7=days.slice(-7);$('avg7').textContent=`Rata-rata ${fmt(last7.reduce((s,x)=>s+x.cal,0)/7)} kcal`;drawBars($('calChart'),days,calcTarget().cal);const ws=[...weights].sort((a,b)=>a.date.localeCompare(b.date)).slice(-14);if(ws.length){const d=ws[ws.length-1].weight-ws[0].weight;$('weightSummary').innerHTML=`<div class="stats-grid"><div class="stat"><span>Terakhir</span><b>${ws.at(-1).weight} kg</b></div><div class="stat"><span>Perubahan</span><b>${d>0?'+':''}${d.toFixed(1)} kg</b></div></div>`;drawLine($('weightChart'),ws);$('weightRecent').innerHTML=ws.slice(-5).reverse().map(x=>`<div class="weight-row"><span>${parseDate(x.date).toLocaleDateString('id-ID',{day:'numeric',month:'short'})}</span><strong>${x.weight} kg</strong></div>`).join('')}else{$('weightSummary').innerHTML='<div class="empty">Belum ada data berat badan.</div>';clearCanvas($('weightChart'));$('weightRecent').innerHTML=''}}
function canvasSize(cv){const dpr=devicePixelRatio||1,w=cv.clientWidth||350,h=Math.round(w*.34);cv.width=w*dpr;cv.height=h*dpr;const c=cv.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);return{c,w,h}}function clearCanvas(cv){const{x=0}=cv;const c=cv.getContext('2d');c.clearRect(0,0,cv.width,cv.height)}function drawBars(cv,a,target){const{c,w,h}=canvasSize(cv),pad=26,gap=5,max=Math.max(target,...a.map(x=>x.cal),1000)*1.15,bw=(w-pad*2-gap*(a.length-1))/a.length;c.clearRect(0,0,w,h);a.forEach((x,i)=>{const bh=x.cal/max*(h-32),left=pad+i*(bw+gap);c.fillStyle='#111827';c.fillRect(left,h-22-bh,bw,bh);if(i%2===0){c.fillStyle='#6b7280';c.font='9px system-ui';c.textAlign='center';c.fillText(parseDate(x.date).toLocaleDateString('id-ID',{day:'numeric'}),left+bw/2,h-7)}});const y=h-22-target/max*(h-32);c.strokeStyle='#9ca3af';c.setLineDash([4,4]);c.beginPath();c.moveTo(pad,y);c.lineTo(w-pad,y);c.stroke();c.setLineDash([])}function drawLine(cv,a){const{c,w,h}=canvasSize(cv);c.clearRect(0,0,w,h);if(!a.length)return;const min=Math.min(...a.map(x=>x.weight))-1,max=Math.max(...a.map(x=>x.weight))+1,p=25,range=Math.max(1,max-min),step=a.length===1?0:(w-p*2)/(a.length-1);c.strokeStyle='#111827';c.lineWidth=3;c.beginPath();a.forEach((x,i)=>{const px=a.length===1?w/2:p+i*step,py=h-p-(x.weight-min)/range*(h-p*2);i?c.lineTo(px,py):c.moveTo(px,py)});c.stroke();a.forEach((x,i)=>{const px=a.length===1?w/2:p+i*step,py=h-p-(x.weight-min)/range*(h-p*2);c.fillStyle='#111827';c.beginPath();c.arc(px,py,4,0,Math.PI*2);c.fill()})}
function renderProfile(){renderProfileFields();const t=calcTarget();$('targetSummary').innerHTML=`<div class="stat"><span>BMR</span><b>${t.bmr}</b></div><div class="stat"><span>TDEE</span><b>${t.tdee}</b></div><div class="stat"><span>Target</span><b>${t.cal}</b></div><div class="stat"><span>Protein</span><b>${t.protein} g</b></div>`;$('pwaStatus').textContent=matchMedia('(display-mode: standalone)').matches?'Terpasang':'Web/PWA'}function renderProfileFields(){$('age').value=profile.age;$('weight').value=profile.weight;$('height').value=profile.height;$('activity').value=profile.activity;$('goal').value=profile.goal;const mt=profile.macroTargets||{};$('macroProteinTarget').value=mt.protein??'';$('macroCarbTarget').value=mt.carb??'';$('macroFatTarget').value=mt.fat??'';document.querySelectorAll('#sexSegment button').forEach(b=>b.classList.toggle('on',b.dataset.v===profile.sex))}async function saveProfile(){const targetText=$('v16WeightTarget').value.trim(),weightTarget=targetText?Number(targetText):null;if(weightTarget!==null&&(!Number.isFinite(weightTarget)||weightTarget<20||weightTarget>400)){toast('Target berat badan harus 20–400 kg atau kosong');return}profile={sex:profile.sex,weightTarget,age:Number($('age').value)||30,weight:Number($('weight').value)||70,height:Number($('height').value)||170,activity:Number($('activity').value)||1.375,goal:Number($('goal').value)||0,macroTargets:Object.fromEntries([['protein','macroProteinTarget',600],['carb','macroCarbTarget',900],['fat','macroFatTarget',300]].filter(x=>$(x[1]).value!=='').map(x=>[x[0],Math.min(x[2],Math.max(0,Number($(x[1]).value)||0))]))};await dbSetKV('profile',profile);renderProfile();renderToday();toast('Profil disimpan')}
function download(name,type,text){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}async function blobToDataURL(blob){return await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(blob)})}
async function dataURLToBlob(url){const r=await fetch(url);return await r.blob()}
async function backup(){try{const data=await v20Snapshot();download(`KaloriKu_backup_${localDate()}.json`,'application/json',JSON.stringify(data,null,2))}catch(e){toast('Backup gagal: '+e.message)}}async function restore(file){return v17OpenRestorePreview(file)}function exportCSV(){
 const cols=['tanggal','waktu_makan','makanan','porsi','jumlah','kalori','protein','karbohidrat','lemak','serat_g','gula_g','natrium_mg','lemak_jenuh_g'];
 const lines=[cols.join(',')];
 for(const l of [...logs].sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt-b.createdAt)){
  const values=[l.date,l.meal,l.name,l.serving,l.qty,l.calories*l.qty,l.protein*l.qty,l.carbs*l.qty,l.fat*l.qty,
   ...['fiber','sugar','sodium','saturatedFat'].map(k=>v17Numeric(l[k])?l[k]*l.qty:'')];
  lines.push(values.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','));
 }
 download('KaloriKu_'+localDate()+'.csv','text/csv;charset=utf-8','\ufeff'+lines.join('\n'));
}
async function startScanner(){if(!window.isSecureContext){toast('Scanner kamera membutuhkan HTTPS');return}$('scannerDialog').showModal();$('scanStatus').textContent='Arahkan kamera ke barcode produk.';try{scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});$('scannerVideo').srcObject=scannerStream;if('BarcodeDetector'in window){const det=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128','code_39']});const loop=async()=>{if(!scannerStream)return;try{const codes=await det.detect($('scannerVideo'));if(codes[0]?.rawValue){await lookupBarcode(codes[0].rawValue);return}}catch{}scanTimer=setTimeout(loop,250)};loop()}else{$('scanStatus').textContent='Browser ini belum mendukung deteksi barcode otomatis. Ketik nomor barcode di bawah.'}}catch(e){$('scanStatus').textContent='Kamera tidak dapat dibuka. Periksa izin kamera atau masukkan barcode manual.'}}
function stopScanner(){if(scanTimer)clearTimeout(scanTimer);scanTimer=null;if(scannerStream){scannerStream.getTracks().forEach(t=>t.stop());scannerStream=null}$('scannerVideo').srcObject=null;$('scannerDialog').close()}
async function lookupBarcode(code){if(!code)return;const local=allFoods.find(f=>f.barcode===code);if(local){stopScanner();$('addDialog').showModal();$('foodSearch').value=local.name;renderAddResults();toast('Produk ditemukan di perangkat');return}if(!navigator.onLine){$('scanStatus').textContent='Barcode belum tersimpan dan perangkat sedang offline.';return}$('scanStatus').textContent=`Mencari ${code}...`;try{const u=`https://world.openfoodfacts.org/api/v3/product/${encodeURIComponent(code)}?fields=product_name,brands,serving_size,nutriments`;const r=await fetch(u);if(!r.ok)throw Error();const j=await r.json(),p=j.product;if(!p?.product_name)throw Error();const n=p.nutriments||{},serv=p.serving_size||'100 g/ml',hasServ=!!p.serving_size&&Number.isFinite(n['energy-kcal_serving']),suffix=hasServ?'_serving':'_100g',cal=Number(n[`energy-kcal${suffix}`]);if(!Number.isFinite(cal))throw Error();const f={id:'off_'+code,name:p.product_name+(p.brands?` · ${p.brands}`:''),category:'Produk kemasan',serving:hasServ?serv:'100 g/ml',calories:cal,protein:Number(n[`proteins${suffix}`])||0,carbs:Number(n[`carbohydrates${suffix}`])||0,fat:Number(n[`fat${suffix}`])||0,source_type:'openfoodfacts',source_ref:`Open Food Facts · ${code}`,barcode:code,...v17FromOFF(n,suffix)};await dbPut('customFoods',f);customFoods.push(f);allFoods=[...staticFoods,...customFoods];stopScanner();$('addDialog').showModal();$('foodSearch').value=f.name;renderAddResults();toast('Produk ditemukan dan disimpan offline')}catch(e){$('scanStatus').textContent='Produk belum ditemukan. Anda bisa memasukkannya dari label kemasan.';$('customBarcode').value=code;}}
function updateOnline(){$('offlineBanner').classList.toggle('hidden',navigator.onLine)}async function registerSW(){if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn(e)}}function showInstall(){$('installBtn').classList.remove('hidden');$('installBtn2').classList.remove('hidden')}async function installPWA(){if(!installPrompt){toast('Di Chrome: menu ⋮ → Tambahkan ke layar utama / Instal aplikasi');return}installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installBtn').classList.add('hidden');$('installBtn2').classList.add('hidden')}
window.addFood=addFood;window.toggleFav=toggleFav;window.removeLog=removeLog;window.saveMealPack=saveMealPack;window.addPack=addPack;window.addEventListener('DOMContentLoaded',()=>init().catch(e=>{console.error(e);document.body.innerHTML='<div style="padding:30px;font-family:system-ui"><h2>KaloriKu gagal dimuat</h2><p>'+esc(e.message)+'</p></div>'}));